apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: social-api # match pods having this label
  template:
    metadata:
      labels:
        component: social-api
    spec:
      containers:
        - name: social-api
          image: tungdn3/recipeshare-social-api:0.0.1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_HTTP_PORTS
              value: "8080"
            - name: ConnectionStrings__DbContextPostgres
              valueFrom:
                secretKeyRef:
                  name: social-secret
                  key: db-connection-string
            - name: ConnectionStrings__AzureServiceBus
              valueFrom:
                secretKeyRef:
                  name: social-secret
                  key: asb-connection-string
            - name: Auth0__Domain
              value: tungdev.au.auth0.com
            - name: Auth0__Audience
              value: https://dev-recipe-share.com
            - name: Auth0__ClientId
              value: xhG3qBbR9Ht3LHnQyG4V3yE4TAKZF9SX
            - name: Auth0__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: social-secret
                  key: auth0-client-secret

---
apiVersion: v1
kind: Service
metadata:
  name: social-api-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: social-api
  ports:
    - port: 8080
      targetPort: 8080
