# certificate.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-cert
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  secretName: letsencrypt-tls
  privateKey:
    rotationPolicy: Always
  commonName: {{ .Values.dns.name }}
  dnsNames:
    - {{ .Values.dns.name }}
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer