apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api-deployment
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: notification-api # match pods having this label
  template:
    metadata:
      labels:
        component: notification-api
    spec:
      containers:
        - name: notification-api
          image: tungdn3/recipeshare-notification-api:{{ default "latest" .Values.notificationImage.tag }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: ConnectionStrings__DbContextPostgres
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: db-connection-string
            - name: ConnectionStrings__AzureServiceBus
              valueFrom:
                secretKeyRef:
                  name: notification-secret
                  key: asb-connection-string

---
apiVersion: v1
kind: Service
metadata:
  name: notification-api-cluster-ip-service
  namespace: {{ default "staging" .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    component: notification-api
  ports:
    - port: 8080
      targetPort: 8080
